FROM openjdk:8
ADD target/stakater-backend-application-0.0.1-SNAPSHOT.jar stakater-backend-application-0.0.1-SNAPSHOT.jar
EXPOSE 8080
ENTRYPOINT["java","-jar","stakater-backend-application-0.0.1-SNAPSHOT.jar"]