FROM openjdk:8
ADD target/stakater-frontend-application-0.0.1-SNAPSHOT.jar stakater-frontend-application-0.0.1-SNAPSHOT.jar
EXPOSE 8081
ENTRYPOINT["java","-jar","stakater-frontend-application-0.0.1-SNAPSHOT.jar"]